server:
  port: ${SERVER_PORT:8079}

spring:
  application:
    name: cms-discovery
  
  # Elasticsearch Configuration
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}
    connection-timeout: ${ELASTICSEARCH_CONNECTION_TIMEOUT:10s}
    socket-timeout: ${ELASTICSEARCH_SOCKET_TIMEOUT:30s}

  # RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          max-interval: 10000ms
          multiplier: 2.0
        default-requeue-rejected: false
        acknowledge-mode: auto

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Logging Configuration
logging:
  level:
    com.thmanyah.services.cmsdiscovery: ${LOG_LEVEL:INFO}
    org.springframework.data.elasticsearch: ${ELASTICSEARCH_LOG_LEVEL:WARN}
    org.springframework.amqp: ${RABBITMQ_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application Configuration
cms-discovery:
  elasticsearch:
    index-name: ${ELASTICSEARCH_INDEX_NAME:cms-shows}
    refresh-policy: ${ELASTICSEARCH_REFRESH_POLICY:wait_for}
    batch-size: ${ELASTICSEARCH_BATCH_SIZE:100}
  
  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:cms.events}
    queue: ${RABBITMQ_QUEUE:cms-discovery.shows}
    routing-key: ${RABBITMQ_ROUTING_KEY:show.created}
    dead-letter-queue: ${RABBITMQ_DLQ:cms-discovery.shows.dlq}
  
  search:
    default-page-size: ${SEARCH_DEFAULT_PAGE_SIZE:20}
    max-page-size: ${SEARCH_MAX_PAGE_SIZE:100}
    highlight-enabled: ${SEARCH_HIGHLIGHT_ENABLED:true}
    fuzzy-enabled: ${SEARCH_FUZZY_ENABLED:true}

# API Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  info:
    title: CMS Discovery API
    description: Public read-only API for searching and discovering content
    version: 1.0.0
    contact:
      name: thmanyah Platform Team
      email: platform@thmanyah.io
